"""Orchestrates outline -> chapters -> cover -> export for a single book.

Runs in a background thread so the request that kicks off generation returns
immediately; the book detail page polls `status` until it flips to
'complete' or 'failed'. A real LLM provider would make this take real time,
so the async shape is deliberate even though the mock provider is instant.
"""

import os
import threading

from . import database, models
from .ai_provider import get_provider


def start_generation(book_id):
    thread = threading.Thread(target=_generate_book, args=(book_id,), daemon=True)
    thread.start()


def _generate_book(book_id):
    book = models.get_book(book_id)
    if book is None:
        return
    try:
        models.update_book_status(book_id, "generating")
        provider = get_provider()

        outline = provider.generate_outline(
            book["title"], book["topic"], book["genre"], book["num_chapters"]
        )
        chapters = []
        for i, chapter_title in enumerate(outline, start=1):
            content = provider.generate_chapter(
                book["title"], book["topic"], book["genre"], chapter_title, i, len(outline)
            )
            models.add_chapter(book_id, i, chapter_title, content)
            chapters.append({"title": chapter_title, "content": content})

        cover_svg = provider.generate_cover_svg(book["title"], book["genre"])
        os.makedirs(database.COVERS_DIR, exist_ok=True)
        os.makedirs(database.EXPORTS_DIR, exist_ok=True)
        cover_path = os.path.join(database.COVERS_DIR, f"{book_id}.svg")
        with open(cover_path, "w") as f:
            f.write(cover_svg)

        from .export_utils import export_epub, export_pdf

        epub_path = os.path.join(database.EXPORTS_DIR, f"{book_id}.epub")
        pdf_path = os.path.join(database.EXPORTS_DIR, f"{book_id}.pdf")
        export_epub(epub_path, book["title"], "Generated by properebooks.com", book["genre"], chapters, cover_svg)
        export_pdf(pdf_path, book["title"], "Generated by properebooks.com", book["genre"], chapters)

        models.update_book_outputs(book_id, cover_path, epub_path, pdf_path)
        models.update_book_status(book_id, "complete")
    except Exception as exc:  # noqa: BLE001 - surfaced to the user, not swallowed
        models.update_book_status(book_id, "failed", error=str(exc))
