"""Orchestrates outline -> chapters -> cover -> marketing package -> export.

Runs in a background thread so the request that kicks off generation returns
immediately; the book detail page polls `status` until it flips to
'complete' or 'failed'. A real LLM provider would make this take real time,
so the async shape is deliberate even though the mock provider is instant.
"""

import json
import os
import threading

from . import billing, database, models
from .ai_provider import get_provider
from .goals import needs_cta


def start_generation(book_id):
    thread = threading.Thread(target=_generate_book, args=(book_id,), daemon=True)
    thread.start()


def _generate_book(book_id):
    book = models.get_book(book_id)
    if book is None:
        return
    try:
        models.update_book_status(book_id, "generating")
        provider = get_provider()
        user = models.get_user_by_id(book["user_id"])
        watermark = billing.watermark_for(user)

        outline = provider.generate_outline(
            book["title"], book["topic"], book["genre"], book["num_chapters"]
        )
        chapters = []
        for i, chapter_title in enumerate(outline, start=1):
            content = provider.generate_chapter(
                book["title"], book["topic"], book["genre"], chapter_title, i, len(outline)
            )
            models.add_chapter(book_id, i, chapter_title, content)
            chapters.append({"title": chapter_title, "content": content})

        marketing = provider.generate_marketing_package(
            book["title"], book["topic"], book["genre"], book["goal"],
            book["author_name"], book["cta_type"], book["cta_target"],
        )
        models.update_book_marketing(book_id, json.dumps(marketing))

        front_matter_parts = [f"Subtitle: {marketing['subtitle']}", marketing["author_bio"]]
        if marketing.get("disclaimer"):
            front_matter_parts.append(marketing["disclaimer"])
        front_matter_content = "\n\n".join(front_matter_parts)
        models.add_chapter(book_id, 0, "About This Book", front_matter_content)
        chapters.insert(0, {"title": "About This Book", "content": front_matter_content})

        if needs_cta(book["goal"]) and book["cta_type"] and marketing.get("cta_text"):
            cta_idx = len(outline) + 1
            models.add_chapter(book_id, cta_idx, "Take the Next Step", marketing["cta_text"])
            chapters.append({"title": "Take the Next Step", "content": marketing["cta_text"]})

        cover_svg = provider.generate_cover_svg(book["title"], book["genre"], watermark=watermark)
        os.makedirs(database.COVERS_DIR, exist_ok=True)
        os.makedirs(database.EXPORTS_DIR, exist_ok=True)
        cover_path = os.path.join(database.COVERS_DIR, f"{book_id}.svg")
        with open(cover_path, "w") as f:
            f.write(cover_svg)

        from .export_utils import export_epub, export_pdf

        epub_path = os.path.join(database.EXPORTS_DIR, f"{book_id}.epub")
        pdf_path = os.path.join(database.EXPORTS_DIR, f"{book_id}.pdf")
        author = book["author_name"] or "Generated by properebooks.com"
        export_epub(epub_path, book["title"], author, book["genre"], chapters, cover_svg)
        export_pdf(pdf_path, book["title"], author, book["genre"], chapters)

        models.update_book_outputs(book_id, cover_path, epub_path, pdf_path)
        models.update_book_status(book_id, "complete")
    except Exception as exc:  # noqa: BLE001 - surfaced to the user, not swallowed
        models.update_book_status(book_id, "failed", error=str(exc))
